name: Vote
main: me.RabidCrab.Vote.Vote
version: 1.9_02
author: RabidCrab
website: http://github.com/rabidcrab
description: Fully customizable voting system designed for admins who want specialized vote types
softdepend: [Vault, AdvancedAFK]
commands:
    vote:
        description: Voting system. /vote help will give you all options available
        usage: /vote
        aliases: [voter, rabidvote, ivote]
permissions:
    vote.voteyes.*:
        description: Gives access to voting yes. 
        usage: vote.voteyes.kick allows the player to vote yes on a kick vote. vote.voteyes.ban for ban, etc.
        default: true
        children:
            vote.voteyes.day: true
            vote.voteyes.night: true
            vote.voteyes.sun: true
            vote.voteyes.rain: true
            vote.voteyes.kick: true
            vote.voteyes.ban: true
            vote.voteyes.restart: true
    vote.voteno.*:
        description: Gives access to voting no. 
        usage: vote.voteyes.kick allows the player to vote no on a kick vote. vote.voteyes.ban for ban, etc.
        default: true
        children:
            vote.voteno.day: true
            vote.voteno.night: true
            vote.voteno.sun: true
            vote.voteno.rain: true
            vote.voteno.kick: true
            vote.voteno.ban: true
            vote.voteno.restart: true
    vote.unbannable:
        description: Makes the user immune to ban votes.
        default: op
    vote.setvalue:
        description: This is used by the vote system to execute vote types that are specific to the plugin.
        default: op
    vote.unkickable:
        description: Makes the user immune to kick votes.
        default: op
    vote.startvote.*:
        description: Gives access to starting a vote type. 
        usage: vote.startvote.kick allows the player to start a kick vote. vote.startvote.ban for ban, etc.
        default: true
        children:
            vote.startvote.day: true
            vote.startvote.night: true
            vote.startvote.sun: true
            vote.startvote.rain: true
            vote.startvote.kick: true
            vote.startvote.ban: true
            vote.startvote.restart: true
    vote.veto:
        description: Allows players to cancel active votes.
        default: op
    vote.reload:
        description: Allows players to reload the plugin.
        default: op